### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by edunham** [j2sol/ansible-buildbot#1]
Hi! 

These configs have been a helpful reference for me since I'm currently learning both Ansible and Buildbot at once. However, I noticed that you don't have any licensing information in the repo to clarify whether it'd be legal for others to use and modify the code. 

GitHub has a handy feature that autocompletes license information if you create a new file called LICENSE through the web interface, if you don't want to add one the old fashioned way :)

Thanks!

**Comment by omgjlk** [comment]
Thanks, I forgot this existed.

**Comment by omgjlk** [comment]
Fixed with d52e52ccbf651b95fe28f638234e61f6dbe8918b
